# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favorate',
            new_name='is_favorite',
        ),
    ]
