# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20160601_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='sasdada/sasas', upload_to=b''),
            preserve_default=False,
        ),
    ]
