# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_song_is_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Songs',
        ),
    ]
