# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20160603_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='upload_file',
            new_name='audio_file',
        ),
    ]
