# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='vloume',
            new_name='volume',
        ),
    ]
